/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.UserRole;

import Business.EcoSystem;
import Business.Enterprise.ConsultationEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HealthConsultationOrganization;
import Business.Organization.Organization;
import Business.Organization.WellnessPlatformOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.UserDoctorWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.apache.log4j.Logger;
import userinterface.UserRole.UserWorkAreaJPanel;
import Business.DB4OUtil.DB4OUtil;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;


/**
 *
 * @author ram
 */
public class UserHealthConsultantRequestJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    private WellnessPlatformOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private  WellnessPlatformOrganization wellnessPlatformOrganization;
    private Network network;
    private EcoSystem system;
   
    private static Logger log = Logger.getLogger(UserWorkAreaJPanel.class);
    private static final String CLASS_NAME = UserWorkAreaJPanel.class.getName();

     private DB4OUtil db = DB4OUtil.getInstance();
    /**
     * Creates new form UserHealthRequestJPanel
     */
    public UserHealthConsultantRequestJPanel(JPanel userProcessContainer,UserAccount userAccount,Enterprise enterprise,WellnessPlatformOrganization organization,EcoSystem system,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.wellnessPlatformOrganization = wellnessPlatformOrganization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        network();
    }
    
    public void network() {
        network.getName();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNameJTxtFld = new javax.swing.JTextField();
        heartBeatJTxtFld = new javax.swing.JTextField();
        docReqJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        jLabel1.setText("Username:");

        jLabel2.setText("Heart beat :");

        userNameJTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameJTxtFldActionPerformed(evt);
            }
        });

        heartBeatJTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heartBeatJTxtFldActionPerformed(evt);
            }
        });

        docReqJButton.setText("Request Doctor Consultation");
        docReqJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docReqJButtonActionPerformed(evt);
            }
        });

        backJButton.setText("<--Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(heartBeatJTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(userNameJTxtFld))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(backJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(docReqJButton)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(userNameJTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(heartBeatJTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(docReqJButton)
                    .addComponent(backJButton))
                .addContainerGap(203, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userNameJTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameJTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameJTxtFldActionPerformed

    private void heartBeatJTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heartBeatJTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heartBeatJTxtFldActionPerformed

    private void docReqJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docReqJButtonActionPerformed
        // TODO add your handling code here:
        // send a 
        if(userNameJTxtFld.getText().trim().equals("") && heartBeatJTxtFld.getText().trim().equals("")){
            JOptionPane.showMessageDialog(null, "please enter the name");
            return;
        }
        
        UserDoctorWorkRequest userHC = new UserDoctorWorkRequest();
        userHC.setUserName(userNameJTxtFld.getText().trim());
        System.out.println("ented username is "+userHC.getUserName());
        userHC.setHeartBeat(Integer.parseInt(heartBeatJTxtFld.getText().trim())); // added username and HeartBeat 
        userHC.setUser(userAccount);
        userHC.setStatus("Requested!!");
        
        //get Doctor Org 
        Organization org = null;
        
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof ConsultationEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof HealthConsultationOrganization) {
                            org = organization;
                            break;
                        }
                    }
                }

            }
        }
        
        System.out.println("Organisation is "+org.getName());

        if (org!= null) {
            org.getWorkQueue().getWorkRequestList().add(userHC);
            // add workqueue to org
            System.out.println("inside queue"+userHC.getUserName());
            userAccount.getWorkQueue().getWorkRequestList().add(userHC); // add workqueue to org 

            JOptionPane.showMessageDialog(null, "Your Request has been sent to Health Consultant. You will recieve an email once the request is ready to process", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        System.out.println(org.getWorkQueue().getWorkRequestList().size());
        db.storeSystem(system);
        ArrayList<WorkRequest> w = org.getWorkQueue().getWorkRequestList();
        
    }//GEN-LAST:event_docReqJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        UserWorkAreaJPanel dw = (UserWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton docReqJButton;
    private javax.swing.JTextField heartBeatJTxtFld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField userNameJTxtFld;
    // End of variables declaration//GEN-END:variables
}
