/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NutritionConsultantRole;

import Business.EcoSystem;
import Business.Enterprise.ConsultationEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HealthConsultationOrganization;
import Business.Organization.NutritionConsultationOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.NutritionistWorkRequest;
import Business.WorkQueue.UserDoctorWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.HealthConsultantRole.HealthConsultantPharmaJPanel;

/**
 *
 * @author shwet
 */
public class NutritionConsultantJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private NutritionConsultationOrganization organization;
    private Network network;
    private EcoSystem system;
    
    private Organization org;
    
    /**
     * Creates new form NutritionConsultationJPanel
     */
    public NutritionConsultantJPanel(JPanel userProcessContainer, UserAccount account, NutritionConsultationOrganization organization, Enterprise enterprise, EcoSystem business,Network network) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = business;
        //network();
        
       
        populateNutritionistTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
    void populateNutritionistTable(){
        
         DefaultTableModel model = (DefaultTableModel)tblNutritionist.getModel();
        
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof ConsultationEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof NutritionConsultationOrganization) {
                            org = organization;
                            break;
                        }
                    }
                }

            }
        }
        model.setRowCount(0);
        for (WorkRequest reqQueue : org.getWorkQueue().getWorkRequestList()){
            NutritionistWorkRequest nutritionistWorkRequest = (NutritionistWorkRequest)reqQueue;
            Object[] row = new Object[7];
            row[0]= nutritionistWorkRequest; // gives the name of the requester
            row[1] = nutritionistWorkRequest.getStatus();
            row[2] = nutritionistWorkRequest.getResult();
            
            model.addRow(row);
        }
        
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNutritionist = new javax.swing.JTable();
        btnProcess = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblNutritionist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "User Name", "Status", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblNutritionist);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 590, 110));

        btnProcess.setText("Consultation");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        
        int selectedHCRequest = tblNutritionist.getSelectedRow();
        
         if(selectedHCRequest >= 0){
             
           NutritionistWorkRequest Nrequest =(NutritionistWorkRequest)tblNutritionist.getValueAt(selectedHCRequest, 0);
           Nrequest.setStatus("Processing");
           
           NutritionistUserJPanel processWorkRequestJPanel = new NutritionistUserJPanel(userProcessContainer, Nrequest);
            userProcessContainer.add("processWorkRequestJPanel", processWorkRequestJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
       }
       else{
           JOptionPane.showMessageDialog(null, "Please Select any row");
    }//GEN-LAST:event_btnProcessActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcess;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNutritionist;
    // End of variables declaration//GEN-END:variables
}
